#spring.application.name=demo
#server.port=8585
#spring.cloud.gateway.discovery.locator.enabled = true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true
#logging.level.root=DEBUG
## First route
#spring.cloud.gateway.routes[0].id=mydotnetcoreapp
#spring.cloud.gateway.routes[0].uri=http://localhost:9091
#spring.cloud.gateway.routes[0].predicates[0]=Path=/mydotnetcoreapp/**
#spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1
#
## Second route
#spring.cloud.gateway.routes[1].id=spring-application
#spring.cloud.gateway.routes[1].uri=http://localhost:8080
#spring.cloud.gateway.routes[1].predicates[0]=Path=/spring-application/**
#spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1
spring:
  application:
    name: demo
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: mydotnetcoreapp
          uri: http://localhost:9091
          predicates:
            - Path=/mydotnetcoreapp/**
          filters:
            - StripPrefix=1
        - id: spring-application
          uri: http://localhost:8080
          predicates:
            - Path=/spring-application/**
          filters:
            - StripPrefix=1
server:
  port: 8585
logging:
  level:
    root: DEBUG
